# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Dojune's Blog
tagline:          ''
description:      'Welcome to my blog.'
url:              http://mindojune.github.io/
baseurl:          /

author:
  name:           'Do June Min'
  url:            https://twitter.com/mindojune

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mindojune/mindojune.github.io
